// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO_7puoadOd4OOPwtNS4DDZZ79wJJqWVY',
    appId: '1:102048503396:web:2f653b366efb6b356e7171',
    messagingSenderId: '102048503396',
    projectId: 'app-fatec-lista-tarefas-d64c0',
    authDomain: 'app-fatec-lista-tarefas-d64c0.firebaseapp.com',
    storageBucket: 'app-fatec-lista-tarefas-d64c0.appspot.com',
    measurementId: 'G-S5T97M9YT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxCtBxenW_7KGOZDp9OlgFOjHjE5ApXxA',
    appId: '1:102048503396:android:6f1fb7e2dede4f826e7171',
    messagingSenderId: '102048503396',
    projectId: 'app-fatec-lista-tarefas-d64c0',
    storageBucket: 'app-fatec-lista-tarefas-d64c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZIEJ5X6Td1J881Juw7UxzdeclqmbRGIA',
    appId: '1:102048503396:ios:a2bc761ea7af69056e7171',
    messagingSenderId: '102048503396',
    projectId: 'app-fatec-lista-tarefas-d64c0',
    storageBucket: 'app-fatec-lista-tarefas-d64c0.appspot.com',
    iosBundleId: 'com.example.app08Firebase',
  );
}
